apiVersion: v1
kind: Service
metadata:
  name: sqlproxy
  labels:
    app: sqlproxy
spec:
  type: NodePort
  ports:
  - name: proxysql
    port: 6033
    nodePort: 30033
  - name: proxysqladmin
    port: 6032
    nodePort: 30032
  selector:
    app: sqlproxy

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlproxy
  labels:
    app: sqlproxy
spec:
#  replicas: 1
  selector:
    matchLabels:
      app: sqlproxy
#  strategy:
#    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sqlproxy
    spec:
      restartPolicy: Always
      containers:
#      - image: proxysql/proxysql
      - image: severalnines/proxysql:1.4.12
        name: proxysql
        volumeMounts:
        - name: proxysql-config
          mountPath: /etc/proxysql.cnf
          subPath: proxysql.cnf
        ports:
        - containerPort: 6033
          name: proxysql-mysql
        - containerPort: 6032
          name: proxysql-admin
      volumes:
      - name: proxysql-config
        configMap:
          name: mysql

---

