apiVersion: v1
kind: Service
metadata:
    name: wp-service
spec:
    type: NodePort
    selector:
        app: wordpress
        tier: frontend
    ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
     
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend

  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - name: wordpress
        image: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: "sqlproxy:6033"
        - name: WORDPRESS_DB_USER
          value: "root"
        - name: WORDPRESS_DB_NAME
          value: "mysql"
        ports:
        - containerPort: 80
          name:  wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: "250m"
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
          
 
